# Generated by Django 5.1.3 on 2024-11-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='targetProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('profile_url', models.URLField(max_length=400)),
                ('posts', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'targetProfileDetails',
            },
        ),
    ]
